title: CubeBit
email: manerfan@163.com
description: CubeBit Composable Applications

lang: zh-CN

baseurl: ""
url: "https://cubewisebit.github.io"
github_username:  CubewiseBit

#remote_theme: pages-themes/slate@v0.2.0
plugins:
  #- jekyll-remote-theme
  - jemoji

# 时区
timezone: Asia/Shanghai
# 编码
encoding: UTF-8

# 如下配置在GitHub Pages默认且中不可修改
# lsi: false
# safe: true
# source: [your repo's top level directory]
# incremental: false
# highlighter: rouge
# gist:
#   noscript: false
# kramdown:
#   math_engine: mathjax
#   syntax_highlighter: rouge