/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  CubebitBoosterSidebar: [
    'cubebit-booster/quickstart',
    {
      type: 'category',
      label: 'CubeBit Booster',
      link: {
        type: 'generated-index',
        title: 'CubeBit Booster',
        description: 'CubeBit Booster',
        slug: '/cubebit-booster',
      },
      items: [
        {
          type: 'doc',
          id: 'cubebit-booster/quickstart',
          label: 'API'
        }
      ]
    }
  ],
   
};

module.exports = sidebars;
